CREATE TABLE IF NOT EXISTS at_receipts (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status_code INT NOT NULL,
    message_id TEXT NOT NULL,
    delivered BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS tg_receipts (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

